encuesta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('vinculacion/', include('usuarios.urls')),
    path('vinculacion/encuestas/', include('encuestas.urls')),
    #comentario
    
]

usuarios/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name='eduacionapp'

#Aqui se determinan las urls a las que se puede acceder a la página
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('home/', views.Home.as_view(), name='home2'),
    path('busqueda/', views.Busqueda.as_view(), name='busqueda'),
    path('login/', views.Login.as_view(), name='login'),
    path('registro-empleador/', views.registroEmpleador, name='registro_empleador'),
    path(r'^logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('registro/', views.RegistroTipoUsuario.as_view(), name='registro'),
    path('verEmpresa/<int:pk>', views.UsuarioEmDetalle.as_view(), name='verempresa'),
    path('verAlumno/<int:pk>', views.UsuarioAlumnoDetalle.as_view(), name='veralumno'),
    path('editar/<int:pk>', views.UsuarioEmEditar.as_view(), name='editar'),
    path('eliminar/<int:pk>', views.UsuarioEmEliminar.as_view(), name='eliminarusuario'),

    path('registro-alumno/<str:grupo>', views.registroAlumno, name='registro_alumno'),
    path('registro-alumnoR/', views.registroAlumnoRecEgresado, name='registro_alumno_recEgresado'),
    path('registro-alumnoRP/', views.registroAlumnoPosgradoRecienEgresado, name='registro_alumnorecien_posgrado'),
    path('registro-alumnoP/', views.registroAlumnoPosgradoEgresado, name='registro_alumno_posgrado'),
]

usuarios/models.py
from django.db import models
from django.conf import settings

class TipoEncuesta(models.Model):
    nombre_encuesta=models.CharField(max_length=200)
    def __str__(self):
        return self.nombre_encuesta

class Preguntas(models.Model):
    texto_pregunta=models.CharField(max_length=200)
    encuesta=models.ForeignKey(TipoEncuesta,on_delete=models.CASCADE)

    def __str__(self):
        return self.texto_pregunta

class TipoPregunta(models.Model):
    nombre_pregunta=models.CharField(max_length=200)
    def __str__(self):
        return self.nombre_pregunta

usuarios/forms.py
from django.forms import TextInput
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from django.contrib.auth.models import Group

### Clase de Form que permite agregar un usuario como alumno sin importar
### si es recien egresado o egresado con antiguedad
class UsuarioForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(UsuarioForm,self).__init__(*args, **kwargs)
        self.fields['password1'].label = 'Introduce tu contraseña'
        self.fields['password2'].label = 'Introduce tu contraseña nuevamente'
        self.fields['password1'].help_text = ''
        self.fields['password2'].help_text = ''
        self.fields['username'].help_text = ''
    # tipo = forms.CharField(widget=forms.HiddenInput())
    
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apellido'}),
            'username': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Matrícula'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Correo electrónico'}),
        }

    #validacion de contraseña

class UsuarioEmpleador(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(UsuarioEmpleador,self).__init__(*args, **kwargs)
        self.fields['password1'].label = 'Introduce tu contraseña'
        self.fields['password2'].label = 'Introduce tu contraseña nuevamente'
        self.fields['password1'].help_text = ''
        self.fields['password2'].help_text = ''
        self.fields['username'].help_text = ''


    class Meta:
        model = User
        fields = ['username', 'first_name', 'email']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Usuario'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre Empresa'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Correo electrónico'}),
        }


class UserProfileChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('first_name','last_name','email')

    def __init__(self, user, *args, **kwargs):
        super(UserProfileChangeForm, self).__init__(*args, **kwargs)
        self.user = user

usuarios/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View

from .forms import UsuarioForm, UsuarioEmpleador, UserProfileChangeForm
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.contrib import messages
from .decorators import unauthenticated_user
from django.utils.decorators import method_decorator
from django.views.generic import ListView,DetailView
from django.shortcuts import render, redirect
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required


### Funcion que permite registrar un empleador, desde la forma UsuarioEmpleador(), agregándolo al grupo
##  'empleador'.
@unauthenticated_user
def registroEmpleador(request):
    form = UsuarioEmpleador()
    if request.method == 'POST':
        form = UsuarioEmpleador(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')

            group = Group.objects.get(name='empleador')
            user.groups.add(group)

            messages.success(request, 'Account was created for ' + username)

            return redirect('eduacionapp:login')

    context = {'form': form}
    return render(request, 'registro_empleadores.html', context)


### Funcion que permite registrar un usuario alumno con años de egreso, desde la forma UsuarioForm(),
### agregándolo al grupo 'alumno'.
@unauthenticated_user
def registroAlumno(request, grupo):
    form = UsuarioForm()
    if request.method == 'POST':
        form = UsuarioForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            group = Group.objects.get(name=grupo)
            user.groups.add(group)

            messages.success(request, 'Account was created for ' + username)

            return redirect('eduacionapp:login')

    context = {'form': form, 'grupo': grupo}
    return render(request, 'registro_alumnos.html', context)

### Funcion que permite registrar un usuario alumno ca punto de egresar de licenciatura, desde la forma UsuarioForm(),
### agregándolo al grupo 'alumno_rec_egresado'.
@unauthenticated_user
def registroAlumnoRecEgresado(request):
    form = UsuarioForm()
    if request.method == 'POST':
        form = UsuarioForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')

            group = Group.objects.get(name='alumno_rec_egresado')
            user.groups.add(group)

            messages.success(request, 'Account was created for ' + username)

            return redirect('eduacionapp:login')

    context = {'form': form}
    return render(request, 'registro_alumnos.html', context)

### Funcion que permite registrar un usuario alumno egresado de posgrado , desde la forma UsuarioForm(),
### agregándolo al grupo 'posgrado_alumno'.
@unauthenticated_user
def registroAlumnoPosgradoRecienEgresado(request):
    form = UsuarioForm()
    if request.method == 'POST':
        form = UsuarioForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')

            group = Group.objects.get(name='posgrado_alumnoRecienE')
            user.groups.add(group)

            messages.success(request, 'Account was created for ' + username)

            return redirect('eduacionapp:login')

    context = {'form': form}
    return render(request, 'registro_alumnos.html', context)

### Funcion que permite registrar un usuario alumno egresado de posgrado , desde la forma UsuarioForm(),
### agregándolo al grupo 'posgrado_alumno'.
@unauthenticated_user
def registroAlumnoPosgradoEgresado(request):
    form = UsuarioForm()
    if request.method == 'POST':
        form = UsuarioForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')

            group = Group.objects.get(name='posgrado_alumno')
            user.groups.add(group)

            messages.success(request, 'Account was created for ' + username)

            return redirect('eduacionapp:login')

    context = {'form': form}
    return render(request, 'registro_alumnos.html', context)

#Esta clase se utiliza para iniciar sesion dentro de la plataforma web
@method_decorator(unauthenticated_user, name='dispatch')
class Login(LoginView):
    template_name = 'login.html'
    form_class = AuthenticationForm
    success_url = reverse_lazy('eduacionapp:admin')

#Esta clase es para organizar el contenido base de la plataforma web
class Home (TemplateView):
    template_name = 'home.html'
    #a ver este comentario es prueba
    success_url = reverse_lazy('eduacionapp:admin')
    usuarios = User.objects.all()
    extra_context = ({'usuarios': usuarios})

    def lista(request):
        usuarios = User.objects.all()
        return render(request, 'home.html', {'usuarios': usuarios})
##Esta clase es para organizar el contenido base de la plataforma web
#
#class Home (TemplateView):
#
#    def home(request):
#        if request.user.is_staff:
#            print("si es staff")
#            plantilla = 'usuarios/home_admin.html'
#            return render(request, plantilla)
#        else:                                                         |
#            print("no es staff")
#            template_name = 'home.html'
#            return render(request, template_name)
#
#        # a ver este comentario es prueba
#        # success_url = reverse_lazy('eduacionapp:admin')
#        # usuarios = User.objects.all()
#        # extra_context = ({'usuarios': usuarios})
#
#    def lista(request):
#        usuarios = User.objects.all()
#        return render(request, 'home.html', {'usuarios': usuarios})
#
##Esta clase es para organizar el contenido base de la plataforma web
#@login_required()
#def homeeee (request):
#    if request.user.is_staff:
#        print("si es staff")
#        plantilla = 'usuarios/home_admin.html'
#        return render(request, plantilla)
#    else:
#        print("no es staff")
#        template_name = 'home.html'
#        return render(request,template_name)
#
#    #a ver este comentario es prueba
#    #success_url = reverse_lazy('eduacionapp:admin')
#    #usuarios = User.objects.all()
#    #extra_context = ({'usuarios': usuarios})
#
class ListaUsuario(ListView):
    model = User

def cuestionario(request):
    plantilla = 'usuarios/cuestionario.html'
    return render(request, plantilla)


class Busqueda(TemplateView):
    template_name = 'barrabusqueda.html'
    success_url = reverse_lazy('eduacionapp:admin')
    usuarios = User.objects.all()
    extra_context = ({'usuarios': usuarios})

class RegistroTipoUsuario(TemplateView):
    template_name = 'registrotipousuario.html'
    success_url = reverse_lazy('eduacionapp:login')
    usuarios = User.objects.all()
    extra_context = ({'usuarios': usuarios})

class UsuarioEmDetalle(TemplateView):
    template_name = 'usuarios/usuarioEmp_detail.html'
    model = User
    extra_context = {'etiquetatipousuario': 'empresa'}

class UsuarioAlumnoDetalle(TemplateView):
    template_name = 'usuarios/usuarioEmp_detail.html'
    model = User
    extra_context = {'etiquetatipousuario': 'alumno'}

class UsuarioEmEditar(UpdateView):
    template_name = 'usuarios/usuarioEmp_form.html'
    model = User
    fields = ['first_name','last_name', 'email']
    success_url = reverse_lazy('eduacionapp:home')

class UsuarioEmEliminar(DeleteView):
    template_name = 'usuarios/user_confirm_delete.html'
    model = User
    success_url = reverse_lazy('eduacionapp:login')

usuarios/templates/barrabusqueda.html
{% load static %}

{% block css %}
    <link rel="stylesheet" href="https://unpkg.com/@trevoreyre/autocomplete-js/dist/style.css" />
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock css %}


    <div class="container col-sm-8 col-md-6 col-lg-4 center busqueda" >
        <div class="row"></div>
        <div id="autocomplete" class="autocomplete">
            <input placeholder="Municipio" aria-label="Municipio" class="autocomplete-input" />
            <ul class="autocomplete-result-list"></ul>
        </div>
    </div>

    <script src="https://unpkg.com/@trevoreyre/autocomplete-js"></script>
    <script>
        new Autocomplete('#autocomplete', {

            search: input => {
                const url = `/buscar-destinos/?destino=${(input)}`
                return new Promise(resolve => {
                    fetch(url)
                        .then(response => response.json())
                        .then(data => {
                            resolve(data.data)
                        })
                })
            },

            renderResult: (result, props) => {
                return `
                    <li ${props}>
                        <div class="wiki-title">
                        ${result.nombre}
                        </div>
                    </li>`
            },

            getResultValue: result => result.nombre,
            onSubmit: result => {
                window.open(`/buscar-viajes/${(result.id)}`, "_self")
            }
        })
    </script>

usuarios/templates/base_bootstrap.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>

        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}"/>

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
        <link rel="shortcut icon" href="{% static '/images/uaz.ico' %}">

        <!-- Ingresado -->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->

        <!---->

        <link rel="stylesheet"
            href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
             crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"2
            crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"
            crossorigin="anonymous"></script>
        <script
          src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
          crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

{% block head %} {% endblock %}
    </head>
    <body >
        <div>
            {% block navbar %} {% endblock %}

            {% block content %}
            {% endblock %}
        </div>

    </body>
{% block footer %}
<!-- Footer-->
        <footer class="py-5 bg-black">
            <div class="container px-5">
                <p class="m-0 text-center text-dark small">Copyright &copy; UAZ 2021</p></div>
        </footer>

{% endblock %}
{% block js %}
    <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <!--<script src="js/scripts.js"></script>-->
        <script src="{% static 'js/scripts.js' %}"></script>
{% endblock %}
</html>

usuarios/templates/base_us.html
{% extends "base_bootstrap.html" %}
{% block navbar %}


<nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
    <div class="container px-5">
        <a class="navbar-brand" href="{% url 'eduacionapp:home2' %}">Vinculación UAZ</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                    {% if request.user.groups.all.0.name == "alumno_rec_egresado" or request.user.groups.all.0.name == "alumno" or request.user.groups.all.0.name == "posgrado_alumno" or request.user.groups.all.0.name == "posgrado_alumnoRecienE" or request.user.is_staff%}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'eduacionapp:veralumno' user.id%}">{{ user.get_username }}</a>
                        </li>
                    {% endif %}
                    {% if request.user.groups.all.0.name == "empleador" %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'eduacionapp:verempresa' user.id%}">{{ user.get_username }}</a>
                        </li>

                    {% endif %}
                     <a class="navbar-brand" href="{% url 'eduacionapp:logout' %}?next={% url 'eduacionapp:login' %}">- Cerrar sesión</a>

                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'eduacionapp:login' %}?next={{request.path}}">Iniciar sesión</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<br>
<br>
<br>
{% endblock %}

usuarios/templates/base_us2.html
{% extends "base_bootstrap.html" %}
{% block navbar %}


<nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
    <div class="container px-5">
        <a class="navbar-brand" href="{% url 'eduacionapp:home' %}">Vinculación UAZ</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                    {% if request.user.groups.all.0.name == "alumno_rec_egresado" or request.user.groups.all.0.name == "alumno" or request.user.groups.all.0.name == "posgrado_alumno" or request.user.groups.all.0.name == "posgrado_alumnoRecienE" or request.user.is_staff%}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'eduacionapp:veralumno' user.id%}">{{ user.get_username }}</a>
                        </li>
                    {% endif %}
                    {% if request.user.groups.all.0.name == "empleador" %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'eduacionapp:verempresa' user.id%}">{{ user.get_username }}</a>
                        </li>

                    {% endif %}
                     <a class="navbar-brand" href="{% url 'eduacionapp:logout' %}?next={% url 'eduacionapp:login' %}">- Cerrar sesión</a>

                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'eduacionapp:login' %}?next={{request.path}}">Iniciar sesión</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% endblock %}

usuarios/templates/login.html
{% extends "base_us.html" %}
{% block title %}
    Login
{% endblock %}
{% load static %}
<style>
    .card {
        margin: 0 auto; /* Added */
        float: none; /* Added */
        margin-bottom: 10px; /* Added */
    }
</style>
{% block content %}
    <div class="container card mb-3" style="width: 18rem;">
        <br>
        <img src="{% static 'images/uaz.jpg' %} " class="card-img   d-flex justify-content-center" alt="Card image cap">
        <br>
        
        {% if form.errors %}
        <div class="alert alert-danger">
            <p>Verifica las credenciales</p>
        </div>
        {% endif %}

        
        {% if messages %}
        <div class="alert alert-success">
            {% for message in messages %}
                <p>{{message}}</p>
            {% endfor %}
        </div>
            
        {% endif %}
            
            
        <form method="post">
            {% csrf_token %}
            <div class="input-group mb-3 justify-content-center">
                <div class="input-group-append">
                    <span class="input-group-text"><i class="fas fa-user"></i></span>
                </div>
                {{ form.username }}
            </div>
            <div class="input-group mb-3 justify-content-center">
                <div class="input-group-append">
                    <span class="input-group-text"><i class="fas fa-key"></i></span>
                </div>
                {{ form.password }}
            </div>
            {% if user.is_anonymous %}
                <div class="d-flex justify-content-center mt-3 login_container">
                    <input class="btn btn-light" type="submit" value="Acceder" href="{% url 'eduacionapp:home' %}">
                </div>
            {% endif %}
            <a class="d-flex card-text justify-content-center mt-3 login_container" href="#">¿Olvidaste tu contraseña?</a>
            <a class="d-flex card-text justify-content-center mt-3 login_container"  href="{% url 'eduacionapp:registro' %}">Registrate</a>

        </form>
        <br>
    </div>


{% endblock %}

usuarios/templates/registro_alumnos.html
{% extends "base_us.html" %}
{% block title %}
    Registrar Nuevo Usuario
{% endblock %}

{% block content %}
    <div class="container card mb-3" style="width: 30rem;">
    <div class="sign-form ">
        <br>
        {% if form.errors %}
            {{form.errors}}
        {% endif %}
     <form method="post">
      {% csrf_token %}
      <div class="input-group mb-3 ">
                <div class="input-group-append">
                    <span class="input-group-text">Matrícula:</span>
                </div>
                {{ form.username }}
            </div>
         <div class="input-group mb-3 ">
                <div class="input-group-append">
                    <span class="input-group-text">Nombre(s):</span>
                </div>
                {{ form.first_name }}
            </div>
         <div class="input-group mb-3 ">
                <div class="input-group-append">
                    <span class="input-group-text">Apellido(s):</span>
                </div>
                {{ form.last_name }}
            </div>
         <div class="input-group mb-3 ">
                <div class="input-group-append">
                    <span class="input-group-text">Correo:</span>
                </div>
                {{ form.email }}
            </div>
         <div class="input-group mb-3 ">
                <div class="input-group-append">
                    <span class="input-group-text">Nueva contraseña:</span>
                </div>
                {{ form.password1 }}
            </div>
         <p class="d-flex card-text mt-3 login_container"> ° La contraseña debe de tener de mínimo 8 caracteres</p>
         <p class="d-flex card-text mt-3 login_container"> ° La contraseña debe no debe de ser completamente numérica</p>
         <div class="input-group mb-3 ">
                <div class="input-group-append">
                    <span class="input-group-text">Confirma contraseña:</span>
                </div>
                {{ form.password2 }}
                {{ form.tipo }}
            </div>
            {% comment %} <input type="hidden" name="tipo" value='{{tipo}}' > {% endcomment %}
     <div class="d-flex justify-content-center mt-3 login_container">
      <button class="btn  btn-success" type="submit">Agregar</button>
     </div>
      <a class="d-flex card-text justify-content-center mt-3 login_container"  href="{% url 'eduacionapp:login' %}">Accede con una cuenta</a>
     </form>
    </div>
    </div>
{% endblock %}

usuarios/templates/registrotipousuario.html
{% extends "base_us2.html" %}
{% block title %}
Registro :: UAZ
{% endblock %}

{% load static %}

{% block content %}

    <header class="bg-dark py-5">
            <div class="container px-5">
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-6">
                        <div class="text-center my-5">
                            <h1 class="display-5 fw-bolder text-white mb-2">Registrate en nuestra plataforma</h1>
                            <p class="lead text-white-50 mb-4">Selecciona el tipo de usuario que mejor te identifique.</p>

                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Features section-->

        <section class="py-5 border-bottom" id="features">
            <div class="container px-5 my-5">
                <div class="row gx-5">
                    <div class="col-lg-4 mb-2 mb-lg-0">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-collection"></i></div>
                        <h2 class="h4 fw-bolder">Alumno a punto de egresar</h2>

                        <a class="text-decoration-none" href="{% url 'eduacionapp:registro_alumno_recEgresado' %}">
                            Alumno de Licenciatura
                            <i class="bi bi-arrow-right"></i>
                        </a>
                        <br>
                        <a class="text-decoration-none" href="{% url 'eduacionapp:registro_alumnorecien_posgrado' %}">
                            Alumno de Posgrado
                            <i class="bi bi-arrow-right"></i>
                        </a>
                    </div>
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-collection"></i></div>
                        <h2 class="h4 fw-bolder">Alumno con tiempo de egresado</h2>
                        <a class="text-decoration-none" href="{% url 'eduacionapp:registro_alumno' 'alumno' %}" id="exalumnoboton">
                            Ex Alumno de Licenciatura
                            <i class="bi bi-arrow-right"></i>
                        </a>
                        <br>
                        <a class="text-decoration-none" href="{% url 'eduacionapp:registro_alumno_posgrado' %}" id="exalumnoposgradoboton">
                            Ex Alumno de Posgrado
                            <i class="bi bi-arrow-right"></i>
                        </a>
                    </div>
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-briefcase-fill"></i></div>
                        <h2 class="h4 fw-bolder">Empleador</h2>
                        <a class="text-decoration-none" href="{% url 'eduacionapp:registro_empleador' %}">
                            Empresa/Organización Empleadora
                            <i class="bi bi-arrow-right"></i>
                        </a>
                    </div>
                </div>
            </div>
        </section>


    {% block js %}
 <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    {% endblock %}
{% endblock %}