encuesta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('vinculacion/', include('usuarios.urls')),
    path('vinculacion/encuestas/', include('encuestas.urls')),
    #comentario
    
]

usuarios/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name='eduacionapp'

#Aqui se determinan las urls a las que se puede acceder a la página
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('home/', views.Home.as_view(), name='home2'),
    path('busqueda/', views.Busqueda.as_view(), name='busqueda'),
    path('login/', views.Login.as_view(), name='login'),
    path('registro-empleador/', views.registroEmpleador, name='registro_empleador'),
    path(r'^logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('registro/', views.RegistroTipoUsuario.as_view(), name='registro'),
    path('verEmpresa/<int:pk>', views.UsuarioEmDetalle.as_view(), name='verempresa'),
    path('verAlumno/<int:pk>', views.UsuarioAlumnoDetalle.as_view(), name='veralumno'),
    path('editar/<int:pk>', views.UsuarioEmEditar.as_view(), name='editar'),
    path('eliminar/<int:pk>', views.UsuarioEmEliminar.as_view(), name='eliminarusuario'),

    path('registro-alumno/<str:grupo>', views.registroAlumno, name='registro_alumno'),
    path('registro-alumnoR/', views.registroAlumnoRecEgresado, name='registro_alumno_recEgresado'),
    path('registro-alumnoRP/', views.registroAlumnoPosgradoRecienEgresado, name='registro_alumnorecien_posgrado'),
    path('registro-alumnoP/', views.registroAlumnoPosgradoEgresado, name='registro_alumno_posgrado'),
]

usuarios/models.py
from django.db import models
from django.conf import settings

class TipoEncuesta(models.Model):
    nombre_encuesta=models.CharField(max_length=200)
    def __str__(self):
        return self.nombre_encuesta

class Preguntas(models.Model):
    texto_pregunta=models.CharField(max_length=200)
    encuesta=models.ForeignKey(TipoEncuesta,on_delete=models.CASCADE)

    def __str__(self):
        return self.texto_pregunta

class TipoPregunta(models.Model):
    nombre_pregunta=models.CharField(max_length=200)
    def __str__(self):
        return self.nombre_pregunta

usuarios/forms.py
from django.forms import TextInput
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from django.contrib.auth.models import Group

### Clase de Form que permite agregar un usuario como alumno sin importar
### si es recien egresado o egresado con antiguedad
class UsuarioForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(UsuarioForm,self).__init__(*args, **kwargs)
        self.fields['password1'].label = 'Introduce tu contraseña'
        self.fields['password2'].label = 'Introduce tu contraseña nuevamente'
        self.fields['password1'].help_text = ''
        self.fields['password2'].help_text = ''
        self.fields['username'].help_text = ''
    # tipo = forms.CharField(widget=forms.HiddenInput())
    
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apellido'}),
            'username': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Matrícula'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Correo electrónico'}),
        }

    #validacion de contraseña

class UsuarioEmpleador(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(UsuarioEmpleador,self).__init__(*args, **kwargs)
        self.fields['password1'].label = 'Introduce tu contraseña'
        self.fields['password2'].label = 'Introduce tu contraseña nuevamente'
        self.fields['password1'].help_text = ''
        self.fields['password2'].help_text = ''
        self.fields['username'].help_text = ''


    class Meta:
        model = User
        fields = ['username', 'first_name', 'email']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Usuario'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre Empresa'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Correo electrónico'}),
        }


class UserProfileChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('first_name','last_name','email')

    def __init__(self, user, *args, **kwargs):
        super(UserProfileChangeForm, self).__init__(*args, **kwargs)
        self.user = user

usuarios/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View

from .forms import UsuarioForm, UsuarioEmpleador, UserProfileChangeForm
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.contrib import messages
from .decorators import unauthenticated_user
from django.utils.decorators import method_decorator
from django.views.generic import ListView,DetailView
from django.shortcuts import render, redirect
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required


### Funcion que permite registrar un empleador, desde la forma UsuarioEmpleador(), agregándolo al grupo
##  'empleador'.
@unauthenticated_user
def registroEmpleador(request):
    form = UsuarioEmpleador()
    if request.method == 'POST':
        form = UsuarioEmpleador(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')

            group = Group.objects.get(name='empleador')
            user.groups.add(group)

            messages.success(request, 'Account was created for ' + username)

            return redirect('eduacionapp:login')

    context = {'form': form}
    return render(request, 'registro_empleadores.html', context)


### Funcion que permite registrar un usuario alumno con años de egreso, desde la forma UsuarioForm(),
### agregándolo al grupo 'alumno'.
@unauthenticated_user
def registroAlumno(request, grupo):
    form = UsuarioForm()
    if request.method == 'POST':
        form = UsuarioForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            group = Group.objects.get(name=grupo)
            user.groups.add(group)

            messages.success(request, 'Account was created for ' + username)

            return redirect('eduacionapp:login')

    context = {'form': form, 'grupo': grupo}
    return render(request, 'registro_alumnos.html', context)

### Funcion que permite registrar un usuario alumno ca punto de egresar de licenciatura, desde la forma UsuarioForm(),
### agregándolo al grupo 'alumno_rec_egresado'.
@unauthenticated_user
def registroAlumnoRecEgresado(request):
    form = UsuarioForm()
    if request.method == 'POST':
        form = UsuarioForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')

            group = Group.objects.get(name='alumno_rec_egresado')
            user.groups.add(group)

            messages.success(request, 'Account was created for ' + username)

            return redirect('eduacionapp:login')

    context = {'form': form}
    return render(request, 'registro_alumnos.html', context)

### Funcion que permite registrar un usuario alumno egresado de posgrado , desde la forma UsuarioForm(),
### agregándolo al grupo 'posgrado_alumno'.
@unauthenticated_user
def registroAlumnoPosgradoRecienEgresado(request):
    form = UsuarioForm()
    if request.method == 'POST':
        form = UsuarioForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')

            group = Group.objects.get(name='posgrado_alumnoRecienE')
            user.groups.add(group)

            messages.success(request, 'Account was created for ' + username)

            return redirect('eduacionapp:login')

    context = {'form': form}
    return render(request, 'registro_alumnos.html', context)

### Funcion que permite registrar un usuario alumno egresado de posgrado , desde la forma UsuarioForm(),
### agregándolo al grupo 'posgrado_alumno'.
@unauthenticated_user
def registroAlumnoPosgradoEgresado(request):
    form = UsuarioForm()
    if request.method == 'POST':
        form = UsuarioForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')

            group = Group.objects.get(name='posgrado_alumno')
            user.groups.add(group)

            messages.success(request, 'Account was created for ' + username)

            return redirect('eduacionapp:login')

    context = {'form': form}
    return render(request, 'registro_alumnos.html', context)

#Esta clase se utiliza para iniciar sesion dentro de la plataforma web
@method_decorator(unauthenticated_user, name='dispatch')
class Login(LoginView):
    template_name = 'login.html'
    form_class = AuthenticationForm
    success_url = reverse_lazy('eduacionapp:admin')

#Esta clase es para organizar el contenido base de la plataforma web
class Home (TemplateView):
    template_name = 'home.html'
    #a ver este comentario es prueba
    success_url = reverse_lazy('eduacionapp:admin')
    usuarios = User.objects.all()
    extra_context = ({'usuarios': usuarios})

    def lista(request):
        usuarios = User.objects.all()
        return render(request, 'home.html', {'usuarios': usuarios})
##Esta clase es para organizar el contenido base de la plataforma web
#
#class Home (TemplateView):
#
#    def home(request):
#        if request.user.is_staff:
#            print("si es staff")
#            plantilla = 'usuarios/home_admin.html'
#            return render(request, plantilla)
#        else:                                                         |
#            print("no es staff")
#            template_name = 'home.html'
#            return render(request, template_name)
#
#        # a ver este comentario es prueba
#        # success_url = reverse_lazy('eduacionapp:admin')
#        # usuarios = User.objects.all()
#        # extra_context = ({'usuarios': usuarios})
#
#    def lista(request):
#        usuarios = User.objects.all()
#        return render(request, 'home.html', {'usuarios': usuarios})
#
##Esta clase es para organizar el contenido base de la plataforma web
#@login_required()
#def homeeee (request):
#    if request.user.is_staff:
#        print("si es staff")
#        plantilla = 'usuarios/home_admin.html'
#        return render(request, plantilla)
#    else:
#        print("no es staff")
#        template_name = 'home.html'
#        return render(request,template_name)
#
#    #a ver este comentario es prueba
#    #success_url = reverse_lazy('eduacionapp:admin')
#    #usuarios = User.objects.all()
#    #extra_context = ({'usuarios': usuarios})
#
class ListaUsuario(ListView):
    model = User

def cuestionario(request):
    plantilla = 'usuarios/cuestionario.html'
    return render(request, plantilla)


class Busqueda(TemplateView):
    template_name = 'barrabusqueda.html'
    success_url = reverse_lazy('eduacionapp:admin')
    usuarios = User.objects.all()
    extra_context = ({'usuarios': usuarios})

class RegistroTipoUsuario(TemplateView):
    template_name = 'registrotipousuario.html'
    success_url = reverse_lazy('eduacionapp:login')
    usuarios = User.objects.all()
    extra_context = ({'usuarios': usuarios})

class UsuarioEmDetalle(TemplateView):
    template_name = 'usuarios/usuarioEmp_detail.html'
    model = User
    extra_context = {'etiquetatipousuario': 'empresa'}

class UsuarioAlumnoDetalle(TemplateView):
    template_name = 'usuarios/usuarioEmp_detail.html'
    model = User
    extra_context = {'etiquetatipousuario': 'alumno'}

class UsuarioEmEditar(UpdateView):
    template_name = 'usuarios/usuarioEmp_form.html'
    model = User
    fields = ['first_name','last_name', 'email']
    success_url = reverse_lazy('eduacionapp:home')

class UsuarioEmEliminar(DeleteView):
    template_name = 'usuarios/user_confirm_delete.html'
    model = User
    success_url = reverse_lazy('eduacionapp:login')

usuarios/templates/usuarios/cuestionario.html
{% extends "base_us.html" %}
{% block title %}
Vinculación :: UAZ
{% endblock %}

{% load static %}

{% block content %}

<!-- Cosas que muestra para el administrador  -->
{% if request.user.is_staff %}

{% else %}
    {% if user.is_authenticated %}


    <!-- Cosas que muestra para el alumno  -->
        {% if request.user.groups.all.0.name == "alumno_rec_egresado" %}
            <p>Cuestionario para alumno recien egresado</p>
        {% endif %}
        {% if request.user.groups.all.0.name == "empleador" %}
            <p>Cuestionario para Empleador</p>

        {% endif %}

        {% if request.user.groups.all.0.name == "alumno" %}

            <p>Cuestionario para Alumno</p>

        {% endif %}

    {% endif %}
{% endif %}
    {% block js %}
 <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    {% endblock %}
{% endblock %}

usuarios/templates/usuarios/user_confirm_delete.html
{% extends "base_us.html" %}
{% block title %}
Confirmar Eliminar Usuario
{% endblock %}

{% load static %}

{% block content %}
<br>
<div class="container card mb-3 " style="width: 30rem; background:whitesmoke" >
    <div class="text-center">
        <form method="post">
        {% csrf_token %}
        <p>¿Quieres eliminar el usuario "{{ object }}"?</p>
        <input  class="btn btn-danger" type="submit" value="Eliminar">
        <a class="btn btn-success" href="{% url 'eduacionapp:home' %}">Cancelar</a>
    </form>
    </div>

</div>

{% endblock %}

usuarios/templates/usuarios/usuarioEmp_detail.html
{% extends "base_us.html" %}
{% block title %}
Vinculación :: UAZ
{% endblock %}

{% load static %}

{% block content %}

<main class="container">
    <div class="jumbotron">
        <div class="card text-center">
          <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">
              <li class="nav-item">
                <a class="nav-link active" id="nav-editar-tab" href="#">Editar</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" id="nav-eliminar-tab" href="{% url 'eduacionapp:eliminarusuario' user.id %}" >Eliminar</a>
              </li>

            </ul>
          </div>
          <div class="card-body">
            <h2 class="card-title">Detalle de Usuario</h2>
              <div class="a">Usuario</div>
              {{user.username}}
              <div class="a">Nombre de {{ etiquetatipousuario }}:</div>
              {{user.first_name}} {{user.last_name}}
              <br>
              <div class="a">Correo:</div>
              {{user.email}}
              <br>

              <a href="{% url 'eduacionapp:editar' user.id%}" class="btn btn-success">Editar</a>
              <a href="{% url 'eduacionapp:home'%}" class="btn btn-danger">Cancelar</a>


          </div>
        </div>
    </div>
</main>



{% endblock %}

usuarios/templates/usuarios/usuarioEmp_form.html
{% extends "base_us.html" %}
{% block title %}
Vinculación :: UAZ
{% endblock %}

{% load static %}

{% block content %}
<div class="container card mb-3 " style="width: 30rem; background:whitesmoke" >
    <div class="text-center">
        <h2>Editar  Usuario</h2>
        <div class="a">
            <form id="formulario" method="post">
                {% csrf_token %}
                {% for field in form %}
                <div class="field_container">
                    </br>
                    {{field.label_tag}} </br>
                    {{field}}
                </div>
                {% endfor %}
                <div>
                    </br>
                    <button type="submit" class="btn btn-success">Guardar</button>
                    <a href="{% url 'eduacionapp:home'%}" class="btn btn-danger">Cancelar</a>
                    
                </div>
            </br>
            </form>
            
        </div>
    </div>
</div>
    
{% endblock %}